### ISSUE TITLE
Create meta-packages for maintained adapter

### ISSUE THREAD

**Issue by NiR-** [KnpLabs/Gaufrette#478]
After internal discussions at KnpLabs, we've decided to create meta-packages in order to ease installation of adapters, see #466 (solution 3).

Steps:
* Create metapackages in new [Gaufrette](https://github.com/Gaufrette) org:
  * with name following `<adapter-name>-adapter` pattern
  * README.md template [available here](https://gist.github.com/NiR-/08ea9ddbd6f30b427145453ac5154e02)
  * Disable issue tracker and wiki on the repository
* Submit them to packagist
* Update documentation (`gh-pages` branch should be updated)

Adapters (see #464 for deprecated adapters):
* [x] AwsS3: https://github.com/Gaufrette/aws-s3-adapter
* [ ] AzureBlobStorage: https://github.com/Gaufrette/azure-blob-storage-adapter
* [ ] DoctrineDbal: https://github.com/Gaufrette/doctrine-dbal-adapter
* [ ] Flysystem: https://github.com/Gaufrette/flysystem-adapter
* [ ] Ftp: https://github.com/Gaufrette/ftp-adapter
* [ ] GridFS: https://github.com/Gaufrette/gridfs-adapter
* [ ] InMemory: https://github.com/Gaufrette/in-memory-adapter
* [ ] Local: https://github.com/Gaufrette/local-adapter
* [ ] OpenCloud: https://github.com/Gaufrette/opencloud-adapter
* [ ] PhpseclibSftp: https://github.com/Gaufrette/phpseclib-sftp-adapter
* [ ] Zip: https://github.com/Gaufrette/zip-adapter
