### ISSUE TITLE
[1.x] Update meta packages

### ISSUE THREAD

**Issue by nicolasmure** [KnpLabs/Gaufrette#614]
The meta packages for adapters removed on 1.x should be deprecated. The new adapters introduced in 1.x should have their meta packages.

## To Deprecate
- [ ] `gaufrette/opencloud-adapter` metapackage (adapter removed in #533)

## To Create
- [ ] `gaufrette/openstack-adapter` metapackage (adapter introduced in #533)
- [ ] `gaufrette/google-cloud-storage-adapter` metapackage (adapter introduced in #557)
